/**
 *
 * All the Status text and Config names are listed here
 *
 **/

#define STATUS_SUCCESS "Success"
#define STATUS_FAILURE "Failure"
#define STATUS_APPROVED "APPROVED"
#define STATUS_ERROR "Error"
#define STATUS_STOPPING "Stopping"
#define STATUS_PENDING "Pending"
#define STATUS_NA "NA"
#define STATUS_OK "OK"
#define STATUS_NOK "KO"
#define STATUS_REVERSAL_PENDING "ReversalPending"
#define STATUS_TID_MID_EMPTY "TidOrMidEmpty"
#define STATUS_KEYS_NOT_LOADED "keys_not_loaded"
#define STATUS_RECALC_MAC "recalc_mac"

#define CONFIG_WRITE_SUCCESS 0

#define STATE_CARD_PRESENTED "card_presented"
#define STATE_CARD_PROCESSED "card_processed"
#define STATE_CARD_REMOVED "card_removed"
#define STATE_CARD_PRESENTED_ABT "card_presented_abt"

#define SCHEME_RUPAY "RuPay"

#define COMMAND "cmd"
#define COMMAND_STATE "state"
#define COMMAND_DATA "data"
#define COMMAND_STATUS "status"
#define COMMAND_ERROR_CODE "errorCode"
#define COMMAND_SEARCH_CARD "search_card"
#define COMMAND_WRITE_CARD "write_card"
#define COMMAND_ABORT "abort"
#define COMMAND_STOP "stop"
#define COMMAND_GET_CONFIG "get_config"
#define COMMAND_SET_CONFIG "set_config"
#define COMMAND_REBOOT "reboot"
#define COMMAND_FETCH_AUTH "fetch_auth"
#define COMMAND_FETCH_ACK "fetch_ack"
#define COMMAND_GET_VERSION "get_version"
#define COMMAND_CLEAR_REVERSAL "clear_reversal"
#define COMMAND_GET_DEVICE_ID "get_device_id"
#define COMMAND_SET_TIME "set_time"
#define COMMAND_DO_BEEP "do_beep"
#define COMMAND_VERIFY_TERMINAL "verify_terminal"
#define COMMAND_AIRTEL_VERIFY_TERMINAL "airtel_verify_terminal"
#define COMMAND_AIRTEL_HEALTH_CHECK "airtel_health_check"
#define COMMAND_ABORT_POLLING "abort_polling"
#define COMMAND_GET_PENDING_OFFLINE "get_pending_offline_summary"
#define COMMAND_CHANGE_IP "change_ip"
#define COMMAND_CHANGE_ONLY_IP "change_only_ip"
#define COMMAND_CHANGE_ONLY_DNS "change_only_dns"
#define COMMAND_CHANGE_LOG_MODE "change_log_mode"
#define COMMAND_IS_KEY_PRESENT "is_key_present"
#define COMMAND_DESTROY_KEY "destroy_key"
#define COMMAND_DOWNLOAD_FILE "download_file"
#define COMMAND_GET_REVERSAL "get_reversal"
#define COMMAND_DELETE_FILE "delete_file"
#define COMMAND_GET_FIRMWARE_VERSION "get_firmware_version"
#define COMMAND_GET_PRODUCT_ORDER_NUMBER "get_product_order_number"
#define COMMAND_RECALC_MAC "recalc_mac"
#define COMMAND_GATE_OPEN "gate_open"
#define COMMAND_ABT_SUMMARY "abt_summary"
#define COMMAND_ABT_FETCH "abt_fetch"

#define DOWNLOAD_FILE_NAME "download_file_name"
#define DELETE_FILE_NAME "delete_file_name"

#define CHANGE_LOG_MODE "log_mode"
#define LOG_MODE_DEBUG "Debug"
#define LOG_MODE_ERROR "Error"

#define CHANGE_IP_MODE "ip_mode"
#define CHANGE_IP_DNS "dns"
#define CHANGE_IP_DNS2 "dns2"
#define CHANGE_IP_DNS3 "dns3"
#define CHANGE_IP_DNS4 "dns4"
#define CHANGE_IP_SEARCH_DOMAIN "search_domain"
#define CHANGE_IP_ADDRESS "ip_address"
#define CHANGE_IP_NETMASK "netmask"
#define CHANGE_IP_GATEWAY "gateway"

#define IP_MODE_STATIC "static"
#define IP_MODE_DYNAMIC "dynamic"

#define KEY_DATA_LABEL "label"
#define KEY_DATA_ISBDK "isBdk"

#define TIME_DATA_KEY "time"
#define SEARCH_CARD_MODE "mode"
#define SEARCH_CARD_TIMEOUT "timeout"
#define SEARCH_CARD_TRXTYPE "trxtype"
#define SEARCH_CARD_AMOUNT "amount"
#define SEARCH_SINGLE "single"
#define SEARCH_LOOP "loop"
#define SEARCH_MONEY_ADD_TYPE "money_add_type"
#define SEARCH_MONEY_ADD_SOURCE_TXN_ID "money_add_source_txn"
#define SEARCH_SERVICE_ID "service_id"
#define SEARCH_IS_SERVICE_BLOCK "is_service_block"
#define SEARCH_CARD_CHECK_DATE "check_date"

#define WRITE_CARD_AMOUNT "amount"
#define WRITE_CARD_SERVICE_DATA "servicedata"

#define GATE_OPEN_GATE_STATUS "gate_status"

#define VERIFY_TRM_TID "tid"
#define VERIFY_TRM_MID "mid"

#define FETCH_AUTH_ID "fetchid"
#define FETCH_MAX_RECORDS "maxrecords"
#define FETCH_STATUS "fetchstatus"
#define FETCH_MODE "mode"

#define FETCH_SKIP "skipRecords"

#define TRXTYPE_PURCHASE "purchase"
#define TRXTYPE_BALANCE_INQUIRY "balance_inquiry"
#define TRXTYPE_BALANCE_UPDATE "balance_update"
#define TRXTYPE_SERVICE_CREATE "service_create"
#define TRXTYPE_MONEY_ADD "money_add"
#define TXNMODE_CARD "CARD"
#define HOST_TXN_FAIL "FAIL"

#define VERSION_KEY "version"
#define CODE_KEY "code"
#define DEVICE_ID_KEY "deviceid"

#define CONFIG_KEY "config"
#define CONFIG_KEY_IP "ip"
#define CONFIG_KEY_PORT "port"
#define CONFIG_KEY_TERMINALID "terminalId"
#define CONFIG_KEY_MERCHANT_ID "merchantId"
#define CONFIG_KEY_CLIENT_ID "clientId"
#define CONFIG_KEY_CLIENT_NAME "clientName"
#define CONFIG_KEY_HOST_VERSION "hostVersion"
#define CONFIG_KEY_TXNTIMEOUT "txnTimeOut"
#define CONFIG_KEY_MAX_RETRY "maxRetry"
#define CONFIG_KEY_HOST_PROCESS_TIMEOUT "hostProcessTimeInMinutes"
#define CONFIG_KEY_REVERSAL_PROCESS_TIMEOUT "reversalTimeInMinutes"
#define CONFIG_KEY_WAIT_WRITE_CARD "nsec_awaiting_write"
#define CONFIG_KEY_PSP "psp"
#define CONFIG_KEY_GENERAL "general"
#define CONFIG_KEY_NAME "name"
#define CONFIG_KEY_VERSION "version"
#define CONFIG_KEY_KEYS "keys"
#define CONFIG_KEY_LED_CONFIGS "ledConfigs"
#define CONFIG_KEY_RELEASE_DATE "release_date"
#define CONFIG_KEY_CURR_CODE "currencyCode"
#define CONFIG_KEY_EMV_FILE "emvConfigFile"
#define CONFIG_KEY_HOST_IP "hostIP"
#define CONFIG_KEY_HTTPS_HOST_NAME "httpsHostName"
#define CONFIG_KEY_OFFLINE_URL "offlineUrl"
#define CONFIG_KEY_SERVRICE_CREATION_URL "serviceCreationUrl"
#define CONFIG_KEY_BALANCE_UPDATE_URL "balanceUpdateUrl"
#define CONFIG_KEY_MONEY_LOAD_URL "moneyLoadUrl"
#define CONFIG_KEY_VERIFY_TERMINAL_URL "verifyTerminalUrl"
#define CONFIG_KEY_REVERSAL_URL "reversalUrl"
#define CONFIG_KEY_HOST_PORT "hostPort"
#define CONFIG_KEY_HOST_TXN_TIMEOUT "hostTxnTimeout"
#define CONFIG_KEY_WRITE_CARD_WAIT "writeCardWaitTimeMs"
#define CONFIG_KEY_HOST_MAX_RETRY "hostMaxRetry"
#define CONFIG_KEY_HOST_MAX_RETRY "hostMaxRetry"
#define CONFIG_KEY_TXN_COUNTER "txnCounter"
#define CONFIG_KEY_BATCH_COUNTER "batchCounter"
#define CONFIG_KEY_MAX_OFFLINE_TXN "maxOfflineTransactions"
#define CONFIG_KEY_MIN_REQUIRED_ONLINE "minRequiredForOnline"
#define CONFIG_KEY_KLD_IP "kldIp"
#define CONFIG_KEY_MAX_KEY_INJECTION_TRY "maxKeyInjectionTry"
#define CONFIG_KEY_KEYINJECT_RETRY_DELAY_SEC "keyInjectRetryDelaySec"
#define CONFIG_KEY_FORCE_KEY_INJECTION "forceKeyInjection"
#define CONFIG_KEY_TIMINIG_ENABLED "timingEnabled"
#define CONFIG_KEY_PRINT_DETAIL_TIMING_LOGS "printDetailTimingLogs"
#define CONFIG_KEY_KEY_LABEL "label"
#define CONFIG_KEY_KEY_SLOT "slot"
#define CONFIG_KEY_KEY_MKVERSION "mkVersion"
#define CONFIG_KEY_KEY_AST_ID "astId"
#define CONFIG_KEY_KEY_PKCS_ID "pkcsId"
#define CONFIG_KEY_KEY_TYPE "type"
#define CONFIG_KEY_IS_MAC "isMac"
#define CONFIG_KEY_KEY_KEY_SET_IDENTIFIER "keySetIdentifier"
#define CONFIG_KEY_ZERO_VALUE_TXN "ignoreZeroValueTxn"
#define CONFIG_KEY_BEEP_ON_CARD_FOUND "beepOnCardFound"
#define CONFIG_KEY_PURCHASE_LIMIT "purchaseLimit"
#define CONFIG_KEY_MONEY_ADD_LIMIT "moneyAddLimit"
#define CONFIG_KEY_PRINT_PROCESS_OUTCOME "printProcessOutcome"
#define CONFIG_KEY_ENABLE_APDU_LOG "enableApduLog"
#define CONFIG_KEY_SOCKET_TIMEOUT "socketTimeout"
#define CONFIG_KEY_AUTO_READ_CARD "autoReadCard"
#define CONFIG_KEY_DEVICE_CODE "deviceCode"
#define CONFIG_KEY_EQUIPMENT_TYPE "equipmentType"
#define CONFIG_KEY_EQUIPMENT_CODE "equipmentCode"
#define CONFIG_KEY_STATION_ID "stationId"
#define CONFIG_KEY_STATION_NAME "stationName"
#define CONFIG_KEY_PAYTM_LOG_COUNT "paytmLogCount"
#define CONFIG_KEY_PAYTM_LOG_SIZE "paytmMaxLogSizeKb"
#define CONFIG_KEY_USE_CONFIG_JSON "useConfigJson"
#define CONFIG_KEY_TXN_TYPE_CODE "txnTypeCode"
#define CONFIG_KEY_DEVICE_TYPE "deviceType"
#define CONFIG_KEY_LOCATION_CODE "locationCode"
#define CONFIG_KEY_OPERATOR_CODE "operatorCode"
#define CONFIG_KEY_TARIFF_VER "tariffVersion"
#define CONFIG_KEY_DEVICE_MODE_CODE "deviceModeCode"
#define CONFIG_KEY_GATE_OPEN_WAIT "gateOpenWaitTimeInMs"
#define CONFIG_KEY_ENABLE_ABT "enableAbt"
#define CONFIG_KEY_ABT_HOST_IP "abtIP"
#define CONFIG_KEY_ABT_HOST_NAME "abtHostName"
#define CONFIG_KEY_ABT_HOST_PORT "abtPort"
#define CONFIG_KEY_ABT_TAP_URL "abtTapUrl"
#define CONFIG_KEY_ABT_HOST_WAIT_TIME "abtHostProcessWaitTimeInMinutes"
#define CONFIG_KEY_ABT_RETENTION_DAYS "abtDataRetentionPeriodInDays"
#define CONFIG_KEY_ABT_CLEANUP_TIME "abtCleanupTimeHHMM"
#define CONFIG_KEY_ABT_HOST_PUSH_BATCH_COUNT "abtHostPushBatchCount"
#define CONFIG_KEY_USE_AIRTEL_HOST "useAirtelHost"
#define CONFIG_KEY_AIRTEL_HOST_IP "airtelHostIP"
#define CONFIG_KEY_AIRTEL_HOST_PORT "airtelHostPort"
#define CONFIG_KEY_AIRTEL_HTTPS_HOST_NAME "airtelHttpsHostName"
#define CONFIG_KEY_ARITEL_OFFLINE_URL "airtelOfflineUrl"
#define CONFIG_KEY_AIRTEL_BALANCE_UPDATE_URL "airtelBalanceUpdateUrl"
#define CONFIG_KEY_AIRTEL_HEALTH_CHECK_URL "airtelHealthCheckUrl"
#define CONFIG_KEY_AIRTEL_VERIFY_TERMINAL_URL "airtelVerifyTerminalUrl"
#define CONFIG_KEY_AIRTEL_REVERSAL_URL "airtelReversalUrl"
#define CONFIG_KEY_AIRTEL_SERVICE_CREATION_URL "airtelServiceCreationUrl"
#define CONFIG_KEY_AIRTEL_MONEY_ADD_URL "airtelMoneyAddUrl"
#define CONFIG_KEY_AIRTEL_SIGN_SALT "airtelSignSalt"
#define CONFIG_KEY_LATITUDE "latitude"
#define CONFIG_KEY_LONGITUDE "longitude"

#define LED_ST_WAITING_KEY_INJECTION "waiting_key_injection"
#define LED_ST_KEY_INJECT "key_inject"
#define LED_ST_AWAITING_CARD_SUCCESS "awating_card_success"
#define LED_ST_AWAITING_CARD_FAILURE "awaiting_card_failure"
#define LED_ST_CARD_READ_FAILED "card_read_failed"
#define LED_ST_CARD_PRESENTED "card_presented"
#define LED_ST_WRITE_SUCCESS "write_success"
#define LED_ST_WRITE_FAILED "write_failed"
#define LED_ST_CARD_PROCESSED_SUCCESS "card_processed_success"
#define LED_ST_CARD_PROCESSED_FAILURE "card_processed_failure"
#define LED_ST_CARD_PROCESSED_MSG_SENT "card_processed_success_msg_sent"
#define LED_ST_APP_STARTED "app_started"
#define LED_ST_APP_EXITING "app_exiting"

#define KEY_TYPE_RUPAY_SERVICE "RUPAY_SERVICE"
#define KEY_TYPE_DUKPT_KEY "DUKPT_KEY"

#define HOST_TXN_BALANCE_UPDATE "Balance_Update"
#define HOST_TXN_MONEY_ADD "Money_Add"
#define HOST_POS_CONDITION_CODE_02 "02"
#define HOST_POS_CONDITION_CODE_00 "00"
#define HOST_POS_ENTRY_MODE "071"

#define HOST_ERROR_CATEGORY_TIMEOUT "Timeout"
#define HOST_ERROR_CATEGORY_FAILED "Failed"

#define REVERSAL_CODE_E1 "E1"
#define REVERSAL_CODE_E2 "E2"
#define REVERSAL_CODE_22 "22"

#define STATUS_DEVICE_OFFLINE "device_offline"

/**
 * Max counter for Transaction and Batch, after which the counter will
 * be reset to 0
 **/
#define MAX_TXN_COUNTER 999999
#define MAX_BATCH_COUNTER 999999
