/**
 * All the application error codes
 **/

#define ERR_GENERIC 0
#define ERR_FETCH_ID_NOT_AVAILABLE 1
#define ERR_DEVICE_IN_STOPPING 2
#define ERR_ALREADY_SEARCHING 3
#define ERR_CARD_NOT_PRESENTED 4
#define ERR_BALANCE_INQUIRY_LOOP_NOT_SUPPORTED 5
#define ERR_BALANCE_UPDATE_LOOP_NOT_SUPPORTED 6
#define ERR_CREATE_TXN_THREAD_FAILED 7
#define ERR_NOT_IN_LOOP_MODE 8
#define ERR_SQL_STATEMENT_PREPARE_FAILED 9
#define ERR_SQL_DELETE_FAILED 10
#define CONFIG_NOT_AVAILABLE 11
#define ERR_SET_TIME_FAILED 12
#define ERR_MONEY_ADD_AMOUNT_NOT_AVAILABLE 13
#define ERR_CARD_PRESENTED_STATE_CANNOT_REBOOT 14
#define ERR_ONGOING_TRANSACTION 15
#define ERR_FILE_NOT_FOUND 16
#define ERR_ONGOING_RECALC_MAC 17
#define ERR_MONEY_ADD_WRONG_TYPE 18
#define ERR_MONEY_MISSING_SOURCE_TXN 19
